import { Property, City, Neighborhood, Broker } from "./types";

export const BROKERS: Broker[] = [
  {
    id: "b1",
    slug: "abebe-tesfaye",
    name: "Abebe Tesfaye",
    avatar: "/images/avatar_abebe.png",
    agencyName: "Bole Premier Real Estate",
    verified: true,
    phone: "+251 911 234 567",
    email: "abebe@bolepremier.et",
    rating: 4.9,
    reviewsCount: 38,
    activeListingsCount: 14,
    languages: ["Amharic", "English"],
    responseTime: "Under 15 minutes",
    specializedAreas: ["Bole Medhanialem", "Kazanchis", "Old Airport"],
    bio: "Certified Ethiopian real estate consultant with 8+ years specializing in physically verified diplomatic residences and luxury modern apartments in Addis Ababa.",
  },
  {
    id: "b2",
    slug: "selamawit-alemu",
    name: "Selamawit Alemu",
    avatar: "/images/avatar_selam.png",
    agencyName: "Capital Verified Homes",
    verified: true,
    phone: "+251 912 345 678",
    email: "selam@capitalhomes.et",
    rating: 4.95,
    reviewsCount: 52,
    activeListingsCount: 19,
    languages: ["Amharic", "English", "Oromiffa"],
    responseTime: "Under 10 minutes",
    specializedAreas: ["CMC", "Kazanchis", "Adama"],
    bio: "Top-rated residential specialist dedicated to transparent Birr leasing, zero middleman markups, and instant field walkthrough inspections.",
  },
  {
    id: "b3",
    slug: "dawit-tadesse",
    name: "Dawit Tadesse",
    avatar: "/images/avatar_abebe.png",
    agencyName: "Hawassa Lakeside Living",
    verified: true,
    phone: "+251 913 456 789",
    email: "dawit@lakeside.et",
    rating: 4.88,
    reviewsCount: 24,
    activeListingsCount: 8,
    languages: ["Amharic", "English", "Sidamu Afoo"],
    responseTime: "Under 30 minutes",
    specializedAreas: ["Hawassa Lake View", "Tabor Sub-City"],
    bio: "Leading Hawassa housing advisor covering lakeside villas, resort-style residences, and modern family apartments.",
  },
  {
    id: "b4",
    slug: "tigist-haile",
    name: "Tigist Haile",
    avatar: "/images/avatar_selam.png",
    agencyName: "Diplomatic Estates Ethiopia",
    verified: true,
    phone: "+251 914 567 890",
    email: "tigist@diplomaticestates.et",
    rating: 4.98,
    reviewsCount: 45,
    activeListingsCount: 11,
    languages: ["Amharic", "English", "French"],
    responseTime: "Under 15 minutes",
    specializedAreas: ["Old Airport", "Bole Rwanda", "Sarbet"],
    bio: "Specializing in high-security G+1 villas, diplomatic compounds with standby generators, and premium expat housing.",
  },
];

export const CITIES: City[] = [
  {
    id: "c1",
    slug: "addis-ababa",
    name: "Addis Ababa",
    image: "/images/city_addis_ababa.png",
    tagline: "Diplomatic Hub & Modern High-Rises",
    startingRentETB: 25000,
    propertiesCount: 342,
    subCities: ["Bole", "Kazanchis", "Old Airport", "CMC", "Sarbet", "Piassa", "Kirkos"],
    description: "Ethiopia's vibrant capital featuring luxury high-rises, diplomatic compounds, modern serviced apartments, and bustling business corridors.",
  },
  {
    id: "c2",
    slug: "hawassa",
    name: "Hawassa",
    image: "/images/city_hawassa.png",
    tagline: "Lakeside Serenity & Resort Residences",
    startingRentETB: 18000,
    propertiesCount: 86,
    subCities: ["Lake View", "Tabor", "Haile Resort Area", "Industrial Park Corridor"],
    description: "Scenic lakeside city known for modern villas, peaceful resort-style homes, and expanding industrial tech quarters.",
  },
  {
    id: "c3",
    slug: "adama",
    name: "Adama",
    image: "/images/city_adama.png",
    tagline: "Expressway Hub & Tech Corridors",
    startingRentETB: 15000,
    propertiesCount: 64,
    subCities: ["Expressway Hub", "Central Adama", "Nazreth Road"],
    description: "Fast-growing trade and tech hub just 45 minutes from Addis Ababa via the Expressway.",
  },
  {
    id: "c4",
    slug: "bahir-dar",
    name: "Bahir Dar",
    image: "/images/city_bahir_dar.png",
    tagline: "Lake Tana Waterfront & Quiet Suburbs",
    startingRentETB: 16000,
    propertiesCount: 52,
    subCities: ["Tana Waterfront", "Kebele 14", "University Area"],
    description: "Lakeside city featuring waterfront apartments, quiet residential greenery, and cultural charm.",
  },
];

export const NEIGHBORHOODS: Neighborhood[] = [
  {
    id: "n1",
    slug: "bole-medhanialem",
    name: "Bole Medhanialem",
    subCity: "Bole",
    city: "Addis Ababa",
    heroImage: "/images/hero_property.png",
    averageRentETB: 55000,
    propertiesCount: 112,
    securityScore: 9.8,
    generatorPenetration: "95% Standby Coverage",
    waterReliability: "10,000L Reserve Average",
    lifestyleTags: ["Diplomatic", "Cafes & Dining", "24/7 Security", "Airport Access"],
    description: "Addis Ababa's premier diplomatic and luxury hub, home to international embassies, upscale shopping malls, and modern residential high-rises.",
  },
  {
    id: "n2",
    slug: "kazanchis-central",
    name: "Kazanchis Central",
    subCity: "Kirkos",
    city: "Addis Ababa",
    heroImage: "/images/hero_home_away.jpg",
    averageRentETB: 42000,
    propertiesCount: 84,
    securityScore: 9.4,
    generatorPenetration: "90% Standby Coverage",
    waterReliability: "8,000L Reserve Average",
    lifestyleTags: ["UN & AU District", "Walkable", "Modern Studios", "Financial Hub"],
    description: "Located steps from the United Nations Economic Commission and commercial centers, ideal for diplomats and young professionals.",
  },
  {
    id: "n3",
    slug: "old-airport-diplomatic",
    name: "Old Airport Diplomatic",
    subCity: "Nifas Silk-Lafto",
    city: "Addis Ababa",
    heroImage: "/images/hero_property.png",
    averageRentETB: 75000,
    propertiesCount: 65,
    securityScore: 9.9,
    generatorPenetration: "98% Standby Coverage",
    waterReliability: "15,000L Reserve Average",
    lifestyleTags: ["G+1 Villas", "International Schools", "Quiet Greenery", "High Security"],
    description: "Exclusive residential neighborhood favored by international diplomats, featuring spacious G+1 villas with lush private gardens.",
  },
  {
    id: "n4",
    slug: "cmc-residential",
    name: "CMC Residential",
    subCity: "Yeka",
    city: "Addis Ababa",
    heroImage: "/images/hero_home_away.jpg",
    averageRentETB: 35000,
    propertiesCount: 94,
    securityScore: 9.2,
    generatorPenetration: "85% Standby Coverage",
    waterReliability: "7,000L Reserve Average",
    lifestyleTags: ["Family Friendly", "Light Rail Access", "Spacious Apartments", "Quiet"],
    description: "Rapidly expanding residential suburb offering modern apartment complexes, excellent light rail connectivity, and quiet family living.",
  },
];

export const PROPERTIES: Property[] = [
  {
    id: "p1",
    slug: "bole-medhanialem-luxury-residence",
    title: "Bole Medhanialem Modern G+1 Villa",
    propertyType: "G+1 Residence",
    rentETB: 65000,
    city: "Addis Ababa",
    subCity: "Bole",
    neighborhood: "Bole Medhanialem",
    address: "Bole Road, Near Japan Embassy",
    bedrooms: 4,
    bathrooms: 3.5,
    areaSqm: 320,
    heroImage: "/images/hero_home_away.jpg",
    galleryImages: [
      "/images/hero_home_away.jpg",
      "/images/hero_property.png",
      "/images/city_addis_ababa.png",
    ],
    verified: true,
    fieldAgentNotes: "Field verified on 2026-07-28. Auto-switch 45kVA standby generator tested clean. 12,000L underground water tank verified operational. Legal title deed checked.",
    generator: true,
    waterTank: true,
    parking: true,
    furnished: true,
    securityGuard: true,
    balcony: true,
    featured: true,
    trending: true,
    broker: BROKERS[0],
    lat: 8.995,
    lng: 38.788,
    description: "Exceptional G+1 luxury villa situated in the quiet diplomatic enclave of Bole Medhanialem. Features a spacious living room with floor-to-ceiling glass windows, custom teak cabinetry, standby generator with automatic transfer switch, 12,000L water reserve, and full 24/7 security guard post.",
    availableDate: "Immediate",
  },
  {
    id: "p2",
    slug: "kazanchis-serviced-studio-apartment",
    title: "Kazanchis Executive Serviced Studio",
    propertyType: "Studio",
    rentETB: 28000,
    city: "Addis Ababa",
    subCity: "Kirkos",
    neighborhood: "Kazanchis Central",
    address: "ECA Road, Opp. Intercontinental",
    bedrooms: 1,
    bathrooms: 1,
    areaSqm: 65,
    heroImage: "/images/hero_property.png",
    galleryImages: [
      "/images/hero_property.png",
      "/images/hero_home_away.jpg",
      "/images/city_addis_ababa.png",
    ],
    verified: true,
    fieldAgentNotes: "Physically audited by Senior Agent Selamawit. Fiber optic internet connected, card-key access lock, standby generator covers elevators and all wall sockets.",
    generator: true,
    waterTank: true,
    parking: true,
    furnished: true,
    securityGuard: true,
    balcony: false,
    featured: true,
    recentlyAdded: true,
    broker: BROKERS[1],
    lat: 9.012,
    lng: 38.766,
    description: "Sleek executive studio located 3 minutes walk from the UN ECA complex in Kazanchis. Fully furnished with Italian furniture, high-speed fiber internet, weekly housekeeping included in rent, and full power backup.",
    availableDate: "Aug 1, 2026",
  },
  {
    id: "p3",
    slug: "old-airport-diplomatic-compound-villa",
    title: "Old Airport Diplomatic Family Compound",
    propertyType: "Villa",
    rentETB: 95000,
    city: "Addis Ababa",
    subCity: "Nifas Silk-Lafto",
    neighborhood: "Old Airport Diplomatic",
    address: "Golf Club Road",
    bedrooms: 5,
    bathrooms: 4.5,
    areaSqm: 450,
    heroImage: "/images/city_addis_ababa.png",
    galleryImages: [
      "/images/city_addis_ababa.png",
      "/images/hero_home_away.jpg",
      "/images/hero_property.png",
    ],
    verified: true,
    fieldAgentNotes: "Inspected by Agent Tigist Haile. Perimeter electric fence operational, guardhouse with private toilet, 20,000L dual water tank system with booster pump.",
    generator: true,
    waterTank: true,
    parking: true,
    furnished: false,
    securityGuard: true,
    balcony: true,
    featured: true,
    trending: true,
    broker: BROKERS[3],
    lat: 8.980,
    lng: 38.740,
    description: "Palatial 5-bedroom diplomatic villa with expansive mature gardens, staff quarters, guardhouse, and double garage. Equipped with heavy-duty diesel generator capable of running AC units and full household loads continuous.",
    availableDate: "Immediate",
  },
  {
    id: "p4",
    slug: "cmc-modern-3br-apartment",
    title: "CMC Sun-Drenched 3 Bedroom Apartment",
    propertyType: "Apartment",
    rentETB: 38000,
    city: "Addis Ababa",
    subCity: "Yeka",
    neighborhood: "CMC Residential",
    address: "CMC Tsehay Real Estate Complex",
    bedrooms: 3,
    bathrooms: 2,
    areaSqm: 140,
    heroImage: "/images/hero_home_away.jpg",
    galleryImages: [
      "/images/hero_home_away.jpg",
      "/images/city_addis_ababa.png",
    ],
    verified: true,
    fieldAgentNotes: "Audited on 2026-07-25. 7th floor elevator standby generator power verified. Quiet corner unit with panoramic view of Yeka Hills.",
    generator: true,
    waterTank: true,
    parking: true,
    furnished: true,
    securityGuard: true,
    balcony: true,
    trending: true,
    recentlyAdded: true,
    broker: BROKERS[1],
    lat: 9.025,
    lng: 38.810,
    description: "Bright and spacious 3-bedroom apartment on 7th floor of Tsehay Real Estate. Enjoy sweeping views of Yeka Hills, private balcony, underground parking slot, and quiet secure environment.",
    availableDate: "Immediate",
  },
  {
    id: "p5",
    slug: "hawassa-lake-view-resort-villa",
    title: "Hawassa Waterfront Lake View Residence",
    propertyType: "Villa",
    rentETB: 48000,
    city: "Hawassa",
    subCity: "Lake View",
    neighborhood: "Lake View Corridor",
    address: "Near Haile Resort Boulevard",
    bedrooms: 3,
    bathrooms: 3,
    areaSqm: 280,
    heroImage: "/images/city_hawassa.png",
    galleryImages: [
      "/images/city_hawassa.png",
      "/images/hero_home_away.jpg",
    ],
    verified: true,
    fieldAgentNotes: "Verified by Agent Dawit Tadesse. Direct lake view from master bedroom balcony, solar water heater installed, quiet resort neighborhood.",
    generator: true,
    waterTank: true,
    parking: true,
    furnished: true,
    securityGuard: true,
    balcony: true,
    featured: true,
    broker: BROKERS[2],
    lat: 7.050,
    lng: 38.470,
    description: "Tranquil 3-bedroom lakeside villa offering panoramic sunset views over Lake Hawassa. Features open lawn garden, modern kitchen, solar water heater, and 24/7 security guard.",
    availableDate: "Aug 5, 2026",
  },
  {
    id: "p6",
    slug: "adama-expressway-modern-2br",
    title: "Adama Tech Corridor 2BR Apartment",
    propertyType: "Apartment",
    rentETB: 22000,
    city: "Adama",
    subCity: "Expressway Hub",
    neighborhood: "Adama Central",
    address: "Adama Expressway Entrance",
    bedrooms: 2,
    bathrooms: 2,
    areaSqm: 110,
    heroImage: "/images/city_adama.png",
    galleryImages: [
      "/images/city_adama.png",
      "/images/hero_property.png",
    ],
    verified: true,
    fieldAgentNotes: "Audited by Selamawit Alemu. Brand new building completed 2026. Elevator standby generator and private water tank.",
    generator: true,
    waterTank: true,
    parking: true,
    furnished: false,
    securityGuard: true,
    balcony: true,
    recentlyAdded: true,
    broker: BROKERS[1],
    lat: 8.540,
    lng: 39.270,
    description: "Modern 2-bedroom apartment situated right at the Adama Expressway gateway. Ideal for commuting executives or local tech workers.",
    availableDate: "Immediate",
  },
  {
    id: "p7",
    slug: "bahir-dar-tana-waterfront-penthouse",
    title: "Bahir Dar Lake Tana Waterfront Penthouse",
    propertyType: "Penthouse",
    rentETB: 42000,
    city: "Bahir Dar",
    subCity: "Tana Waterfront",
    neighborhood: "Kebele 14",
    address: "Lake Tana Drive",
    bedrooms: 3,
    bathrooms: 3,
    areaSqm: 210,
    heroImage: "/images/city_bahir_dar.png",
    galleryImages: [
      "/images/city_bahir_dar.png",
      "/images/hero_home_away.jpg",
    ],
    verified: true,
    fieldAgentNotes: "Verified waterfront penthouse with wrap-around terrace overlooking Lake Tana source of the Blue Nile.",
    generator: true,
    waterTank: true,
    parking: true,
    furnished: true,
    securityGuard: true,
    balcony: true,
    featured: true,
    broker: BROKERS[0],
    lat: 11.590,
    lng: 37.390,
    description: "Unmatched penthouse residence with wrap-around private terrace right on Lake Tana. Watch pelicans and boats from your living room.",
    availableDate: "Immediate",
  },
  {
    id: "p8",
    slug: "sarbet-diplomatic-2br-furnished",
    title: "Sarbet AU Corridor 2BR Furnished Flat",
    propertyType: "Apartment",
    rentETB: 42000,
    city: "Addis Ababa",
    subCity: "Kirkos",
    neighborhood: "Sarbet",
    address: "Near African Union HQ",
    bedrooms: 2,
    bathrooms: 2,
    areaSqm: 115,
    heroImage: "/images/hero_property.png",
    galleryImages: [
      "/images/hero_property.png",
      "/images/hero_home_away.jpg",
    ],
    verified: true,
    fieldAgentNotes: "Field verified on 2026-07-29. Auto generator, clean elevator, high security building near AU compound.",
    generator: true,
    waterTank: true,
    parking: true,
    furnished: true,
    securityGuard: true,
    balcony: true,
    recentlyAdded: true,
    broker: BROKERS[3],
    lat: 9.001,
    lng: 38.745,
    description: "Turnkey 2-bedroom apartment 5 minutes drive from African Union Headquarters. Modern Scandinavian interior, underground parking, and high-speed internet.",
    availableDate: "Immediate",
  },
];
